# Menus
bindd = SUPER, SPACE, Launch apps, exec, dotfiles walker
bindd = SUPER CTRL, E, Emoji picker, exec, dotfiles walker -m symbols
bindd = SUPER, K, Show key bindings, exec, dotfiles keybindings
bindd = SUPER, M, Restart hyprland, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bindd = , XF86Calculator, Calculator, exec, gnome-calculator

# Aesthetics
bindd = SUPER SHIFT, SPACE, Toggle top bar, exec, dotfiles toggle waybar

# Notifications
bindd = SUPER, COMMA, Dismiss last notification, exec, makoctl dismiss
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, makoctl dismiss --all
bindd = SUPER CTRL, COMMA, Toggle silencing notifications, exec, dotfiles toggle notifications
bindd = SUPER ALT, COMMA, Invoke last notification, exec, makoctl invoke
bindd = SUPER SHIFT ALT, COMMA, Restore last notification, exec, makoctl restore

# Toggles
bindd = SUPER CTRL, I, Toggle locking on idle, exec, dotfiles toggle idle
bindd = SUPER CTRL, N, Toggle nightlight, exec, dotfiles toggle nightlight

# Captures
bindd = , PRINT, Screenshot, exec, dotfiles capture screenshot
bindd = ALT, PRINT, Screenrecording, exec, dotfiles capture screenrecording
bindd = SUPER, PRINT, Color picker, exec, pkill hyprpicker || hyprpicker -a

# Waybar-less information
bindd = SUPER CTRL ALT, T, Show time, exec, notify-send -u low "$(date +"%A %H:%M  ·  %d %B %Y  ·  Week %V")"
bindd = SUPER CTRL ALT, B, Show battery remaining, exec, notify-send -u low "$(dotfiles status battery)"

# Control panels
bindd = SUPER CTRL, A, Audio controls, exec, dotfiles control audio
bindd = SUPER CTRL, B, Bluetooth controls, exec, dotfiles control bluetooth
bindd = SUPER CTRL, W, Wifi controls, exec, dotfiles control wifi
bindd = SUPER CTRL, T, Activity, exec, dotfiles open-tui btop

# Dictation
bindd = SUPER CTRL, X, Toggle dictation, exec, voxtype record toggle
bindd  = , F9, Start dictation (push-to-talk), exec, voxtype record start
binddr = , F9, Stop dictation (push-to-talk),  exec, voxtype record stop

# Zoom
bindd = SUPER CTRL, Z, Zoom in, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 1')
bindd = SUPER CTRL ALT, Z, Reset zoom, exec, hyprctl keyword cursor:zoom_factor 1

# Lock system
bindd = SUPER CTRL, L, Lock system, exec, dotfiles system lock
