# Application bindings
bindd = SUPER, RETURN, Tmux, exec, dotfiles open-or-focus ^tmux-terminal$ "uwsm-app -- xdg-terminal-exec --title=\"tmux-terminal\" --dir=\"$(dotfiles internal-terminal-cwd)\" bash -c \"tmux attach || tmux new -s Work\""
bindd = SUPER ALT, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(dotfiles internal-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, dotfiles open-or-focus-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(dotfiles internal-terminal-cwd)"
bindd = SUPER SHIFT, B, Brave, exec, dotfiles open-or-focus ^brave-origin-beta$ "uwsm-app -- brave-origin-beta"
bindd = SUPER SHIFT ALT, B, Brave (private), exec, uwsm-app -- brave-origin-beta --incognito
bindd = SUPER SHIFT, M, Music, exec, dotfiles open-or-focus-tui ratune
bindd = SUPER SHIFT ALT, M, Music TUI, exec, dotfiles open-or-focus-tui cliamp
bindd = SUPER SHIFT, N, Editor, exec, dotfiles edit
bindd = SUPER SHIFT, D, Docker, exec, dotfiles open-tui lazydocker
bindd = SUPER SHIFT, W, Obsidian, exec, dotfiles open-or-focus ^obsidian$ "uwsm-app -- obsidian"
bindd = SUPER SHIFT, O, Tasks, exec, tuxedo-tasks

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, A, ChatGPT, exec, dotfiles open-or-focus-web-app ChatGPT "https://chatgpt.com"
bindd = SUPER SHIFT, C, Calendar, exec, dotfiles open-or-focus-web-app Calendar "https://nextcloud.elvisgastelum.com/index.php/apps/calendar/dayGridMonth/now"
bindd = SUPER SHIFT, T, Deck, exec, dotfiles open-or-focus-web-app Deck "https://nextcloud.elvisgastelum.com/index.php/apps/deck/"
bindd = SUPER SHIFT, E, Email, exec, dotfiles open-or-focus-web-app "Proton Mail" "https://mail.proton.me/"
bindd = SUPER SHIFT, Y, YouTube, exec, dotfiles open-or-focus-web-app YouTube "https://youtube.com/"
bindd = SUPER SHIFT, G, WhatsApp, exec, dotfiles open-or-focus-web-app WhatsApp "https://web.whatsapp.com/"
bindd = SUPER SHIFT, P, Nextcloud Photos, exec, dotfiles open-or-focus-web-app Photos "https://nextcloud.elvisgastelum.com/index.php/apps/photos/"

# Add extra bindings
bindd = SUPER ALT, SPACE, Dotfiles menu, exec, dotfiles menu
bindd = SUPER, ESCAPE, System menu, exec, dotfiles menu system
bind = SUPER SHIFT, R, exec, alacritty -e ssh work

# Overwrite existing bindings, like putting Dotfiles Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, App launcher, exec, dotfiles walker

# Logitech MX Keys
bind = SUPER SHIFT, S, exec, dotfiles capture screenshot      # Print Screen Button
bind = SUPER, H, exec, voxtype record toggle                 # Dictation Button
bind = SUPER, PERIOD, exec, dotfiles walker -m symbols # Emoji Button
